### ISSUE TITLE
starter package addition

### ISSUE THREAD

**Issue by hturner** [cran-task-views/ReproducibleResearch#10]
1. Which package would you like to suggest? What features does it provide?
starter: Starter Kit for New Projects

    > Get started with new projects by dropping a skeleton of a new project into a new or existing directory, initialise git repositories, and create reproducible environments with the 'renv' package. The package allows for dynamically named files, folders, file content, as well as the functionality to drop individual template files into existing projects.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=starter

3. Which category do you think is the best fit for the package:
project workflows (Workflow framework packages)

**Comment by jdblischak** [comment]
> starter: Starter Kit for New Projects
> https://cran.r-project.org/package=starter

@hturner Looks great! Thanks for submitting

> project workflows (Workflow framework packages)

Though I do have to disagree with the classification. I think that starters is a workflow utility package as opposed to a framework. Similar to usethis, it provides utility functions that are meant to be run once per project to setup infrastructure. Unlike a framework package, it doesn't have any strict requirements and/or assumptions about where files are saved. I of course understand there is some ambiguity in the classifications, but overall the starter package is very similar to other project template generators like prodigenr, RepoGenerator, rrtools, and starters
