### ISSUE TITLE
add rcompendium

### ISSUE THREAD

**Issue by see24** [cran-task-views/ReproducibleResearch#13]
1. Which package would you like to suggest? What features does it provide?
rcompendium
From the [website](https://frbcesab.github.io/rcompendium/index.html):
The aim of the package rcompendium is to make easier the creation of R package/research compendium (i.e. a predefined files/folders structure) so that users can focus on the code/analysis instead of wasting time organizing files.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=rcompendium

3. Which category do you think is the best fit for the package:
project workflows

**Comment by jdblischak** [comment]
Thanks @see24!
