### ISSUE TITLE
codebook & codebookr

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/ReproducibleResearch#14]
1. Which package would you like to suggest? What features does it provide?

codebook & codebookr

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=codebook
https://cran.r-project.org/package=codebookr

3. Which category do you think is the best fit for the package:

project workflows?

**Comment by jdblischak** [comment]
@jpiaskowski Thanks for opening an Issue to suggest more packages!

I'm leaning towards the "Object Conversion Functions" in the literate programming section (which I inherited, and unfortunately haven't had the bandwidth to overhaul how it is organized). These codebook packages provide a function that performs some calculations on a data frame and then exports a nicely formatted document. From a quick skim, it looks like {codebook} supports HTML, PDF, and Word, and {codebookr} supports Word.
