### ISSUE TITLE
parameters package addition

### ISSUE THREAD

**Issue by RPanczak** [cran-task-views/ReproducibleResearch#4]
`parameters` [package](https://easystats.github.io/parameters/)  could be added to the *Object Conversion Functions* of the HTML section

**Comment by jdblischak** [comment]
Thanks @RPanczak! I assume you were referring to the [functions that print tables](https://easystats.github.io/parameters/reference/display.parameters_model.html), so I added it to both the HTML and Markdown sections

**Comment by RPanczak** [comment]
Thanks @jdblischak - i think that would be the two places it'd fit.
